// ============================================================
// EMS Common ValueSets
// Cross-cutting: NV, PN, certification, barrier, situation, protocols
// ============================================================

// ── EMSNotValueVS ─────────────────────────────────────────────
// NEMSIS NV pattern — used across 269 of 657 elements
ValueSet: EMSNotValueVS
Id: vs-ems-not-value
Title: "NEMSIS Not Value (NV)"
Description: "NEMSIS Not Value codes used when a data element is Not Applicable, Not Recorded, or Not Reporting."
* ^url = "http://hl7.org/fhir/us/emscore/ValueSet/vs-ems-not-value"
* ^status = #active
* $nemsis-nv#NV.NotApplicable   "Not Applicable"
* $nemsis-nv#NV.NotRecorded     "Not Recorded"
* $nemsis-nv#NV.NotReporting    "Not Reporting"

// ── EMSPertinentNegativeVS ────────────────────────────────────
// NEMSIS PN pattern — used across 70 of 657 elements
ValueSet: EMSPertinentNegativeVS
Id: vs-ems-pertinent-negative
Title: "NEMSIS Pertinent Negative (PN)"
Description: "NEMSIS Pertinent Negative codes indicating a clinically significant documented absence."
* ^url = "http://hl7.org/fhir/us/emscore/ValueSet/vs-ems-pertinent-negative"
* ^status = #active
* $nemsis-pn#PN.Approximate              "Approximate"
* $nemsis-pn#PN.ContraindicationNoted    "Contraindication Noted"
* $nemsis-pn#PN.DeniedByOrder            "Denied By Order"
* $nemsis-pn#PN.ExamFindingNotPresent    "Exam Finding Not Present"
* $nemsis-pn#PN.MedicationAllergy        "Medication Allergy"
* $nemsis-pn#PN.MedicationAlreadyTaken   "Medication Already Taken"
* $nemsis-pn#PN.NoKnownDrugAllergy       "No Known Drug Allergy"
* $nemsis-pn#PN.NoneReported             "None Reported"
* $nemsis-pn#PN.NotImmunized             "Not Immunized"
* $nemsis-pn#PN.OrderCriteriaNotMet      "Order Criteria Not Met"
* $nemsis-pn#PN.Refused                  "Refused"
* $nemsis-pn#PN.SymptomNotPresent        "Symptom Not Present"
* $nemsis-pn#PN.UnableToComplete         "Unable To Complete"
* $nemsis-pn#PN.Unresponsive             "Unresponsive"

// ── EMSCertificationLevelVS ───────────────────────────────────
// NEMSIS: eCrew.02 - Crew Member Level (Mandatory/National)
ValueSet: EMSCertificationLevelVS
Id: vs-ems-certification-level
Title: "EMS Certification Level"
Description: "NEMSIS eCrew.02 - The certification/licensure level of the EMS crew member."
* ^url = "http://hl7.org/fhir/us/emscore/ValueSet/vs-ems-certification-level"
* ^status = #active
* $nemsis-personnel-level#9925001 "Advanced Emergency Medical Technician (AEMT)"
* $nemsis-personnel-level#9925002 "Emergency Medical Technician - Intermediate"
* $nemsis-personnel-level#9925003 "Emergency Medical Responder (EMR)"
* $nemsis-personnel-level#9925005 "Emergency Medical Technician (EMT)"
* $nemsis-personnel-level#9925007 "Paramedic"
* $nemsis-personnel-level#9925023 "Other Healthcare Professional"
* $nemsis-personnel-level#9925025 "Other Non-Healthcare Professional"
* $nemsis-personnel-level#9925027 "Physician"
* $nemsis-personnel-level#9925029 "Respiratory Therapist"
* $nemsis-personnel-level#9925031 "Student"
* $nemsis-personnel-level#9925033 "Critical Care Paramedic"
* $nemsis-personnel-level#9925035 "Community Paramedicine"
* $nemsis-personnel-level#9925037 "Nurse Practitioner"
* $nemsis-personnel-level#9925039 "Physician Assistant"
* $nemsis-personnel-level#9925041 "Licensed Practical Nurse (LPN)"
* $nemsis-personnel-level#9925043 "Registered Nurse"

// ── EMSBarrierToPatientCareVS ─────────────────────────────────
// NEMSIS: eHistory.01 - Barriers to Patient Care (Required/National)
ValueSet: EMSBarrierToPatientCareVS
Id: vs-ems-barrier-to-patient-care
Title: "EMS Barriers to Patient Care"
Description: "NEMSIS eHistory.01 - Barriers encountered during patient assessment or care."
* ^url = "http://hl7.org/fhir/us/emscore/ValueSet/vs-ems-barrier-to-patient-care"
* ^status = #active
* $nemsis-cs#3101001 "Cultural, Custom, Religious"
* $nemsis-cs#3101003 "Developmentally Impaired"
* $nemsis-cs#3101005 "Hearing Impaired"
* $nemsis-cs#3101007 "Language"
* $nemsis-cs#3101009 "None Noted"
* $nemsis-cs#3101011 "Obesity"
* $nemsis-cs#3101013 "Physical Barrier (Unable to Access Patient)"
* $nemsis-cs#3101015 "Physically Impaired"
* $nemsis-cs#3101017 "Physically Restrained"
* $nemsis-cs#3101019 "Psychologically Impaired"
* $nemsis-cs#3101021 "Sight Impaired"
* $nemsis-cs#3101023 "Speech Impaired"
* $nemsis-cs#3101025 "Unattended or Unsupervised (including minors)"
* $nemsis-cs#3101027 "Unconscious"
* $nemsis-cs#3101029 "Uncooperative"
* $nemsis-cs#3101031 "State of Emotional Distress"
* $nemsis-cs#3101033 "Alcohol Use, Suspected"
* $nemsis-cs#3101035 "Drug Use, Suspected"

// ── EMSIncidentTypeVS ─────────────────────────────────────────
// NEMSIS: eSituation.07 - Chief Complaint Anatomic Location (Required/National)
// NOTE: The extension EMSIncidentType is titled "EMS Incident Type" but maps to
// eSituation.07 (Chief Complaint Anatomic Location). Codes are anatomic regions.
ValueSet: EMSIncidentTypeVS
Id: vs-ems-incident-type
Title: "EMS Chief Complaint Anatomic Location"
Description: "NEMSIS eSituation.07 - The anatomic location of the patient's chief complaint."
* ^url = "http://hl7.org/fhir/us/emscore/ValueSet/vs-ems-incident-type"
* ^status = #active
* $nemsis-situation#2807001 "Abdomen"
* $nemsis-situation#2807003 "Back"
* $nemsis-situation#2807005 "Chest"
* $nemsis-situation#2807007 "Extremity-Lower"
* $nemsis-situation#2807009 "Extremity-Upper"
* $nemsis-situation#2807011 "General/Global"
* $nemsis-situation#2807013 "Genitalia"
* $nemsis-situation#2807015 "Head"
* $nemsis-situation#2807017 "Neck"

// ── EMSProtocolUsedVS ─────────────────────────────────────────
// NEMSIS: eProtocols.01 - Protocols Used (Required/National)
ValueSet: EMSProtocolUsedVS
Id: vs-ems-protocol-used
Title: "EMS Protocols Used"
Description: "NEMSIS eProtocols.01 - EMS protocol(s) followed during the response."
* ^url = "http://hl7.org/fhir/us/emscore/ValueSet/vs-ems-protocol-used"
* ^status = #active
* $nemsis-procedures#9914001 "Airway"
* $nemsis-procedures#9914003 "Airway-Failed"
* $nemsis-procedures#9914005 "Airway-Obstruction/Foreign Body"
* $nemsis-procedures#9914007 "Airway-Rapid Sequence Induction (RSI-Paralytic)"
* $nemsis-procedures#9914009 "Airway-Sedation Assisted (Non-Paralytic)"
* $nemsis-procedures#9914011 "Cardiac Arrest-Asystole"
* $nemsis-procedures#9914013 "Cardiac Arrest-Hypothermia-Therapeutic"
* $nemsis-procedures#9914015 "Cardiac Arrest-Pulseless Electrical Activity"
* $nemsis-procedures#9914017 "Cardiac Arrest-Ventricular Fibrillation/Pulseless Ventricular Tachycardia"
* $nemsis-procedures#9914019 "Cardiac Arrest-Post Resuscitation Care"
* $nemsis-procedures#9914021 "Environmental-Altitude Sickness"
* $nemsis-procedures#9914023 "Environmental-Cold Exposure"
* $nemsis-procedures#9914025 "Environmental-Frostbite/Cold Injury"
* $nemsis-procedures#9914027 "Environmental-Heat Exposure/Exhaustion"
* $nemsis-procedures#9914029 "Environmental-Heat Stroke/Hyperthermia"
* $nemsis-procedures#9914031 "Environmental-Hypothermia"
* $nemsis-procedures#9914033 "Exposure-Airway/Inhalation Irritants"
* $nemsis-procedures#9914035 "Exposure-Biological/Infectious"
* $nemsis-procedures#9914037 "Exposure-Blistering Agents"
* $nemsis-procedures#9914041 "Exposure-Chemicals to Eye"
* $nemsis-procedures#9914043 "Exposure-Cyanide"
* $nemsis-procedures#9914045 "Exposure-Explosive/Blast Injury"
* $nemsis-procedures#9914047 "Exposure-Nerve Agents"
* $nemsis-procedures#9914049 "Exposure-Radiologic Agents"
* $nemsis-procedures#9914051 "General-Back Pain"
* $nemsis-procedures#9914053 "General-Behavioral/Patient Restraint"
* $nemsis-procedures#9914055 "General-Cardiac Arrest"
* $nemsis-procedures#9914057 "General-Dental Problems"
* $nemsis-procedures#9914059 "General-Epistaxis"
* $nemsis-procedures#9914061 "General-Fever"
* $nemsis-procedures#9914063 "General-Individualized Patient Protocol"
* $nemsis-procedures#9914065 "General-Indwelling Medical Devices/Equipment"
* $nemsis-procedures#9914067 "General-IV Access"
* $nemsis-procedures#9914069 "General-Medical Device Malfunction"
* $nemsis-procedures#9914071 "General-Pain Control"
* $nemsis-procedures#9914073 "General-Spinal Immobilization/Clearance"
* $nemsis-procedures#9914075 "General-Universal Patient Care/Initial Patient Contact"
* $nemsis-procedures#9914077 "Injury-Amputation"
* $nemsis-procedures#9914079 "Injury-Bites and Envenomations-Land"
* $nemsis-procedures#9914081 "Injury-Bites and Envenomations-Marine"
* $nemsis-procedures#9914083 "Injury-Bleeding/Hemorrhage Control"
* $nemsis-procedures#9914085 "Injury-Burns-Thermal"
* $nemsis-procedures#9914087 "Injury-Cardiac Arrest"
* $nemsis-procedures#9914089 "Injury-Crush Syndrome"
* $nemsis-procedures#9914091 "Injury-Diving Emergencies"
* $nemsis-procedures#9914093 "Injury-Drowning/Near Drowning"
* $nemsis-procedures#9914095 "Injury-Electrical Injuries"
* $nemsis-procedures#9914097 "Injury-Extremity"
* $nemsis-procedures#9914099 "Injury-Eye"
* $nemsis-procedures#9914101 "Injury-Head"
* $nemsis-procedures#9914103 "Injury-Impaled Object"
* $nemsis-procedures#9914105 "Injury-Multisystem"
* $nemsis-procedures#9914107 "Injury-Spinal Cord"
* $nemsis-procedures#9914109 "Medical-Abdominal Pain"
* $nemsis-procedures#9914111 "Medical-Allergic Reaction/Anaphylaxis"
* $nemsis-procedures#9914113 "Medical-Altered Mental Status"
* $nemsis-procedures#9914115 "Medical-Bradycardia"
* $nemsis-procedures#9914117 "Medical-Cardiac Chest Pain"
* $nemsis-procedures#9914119 "Medical-Diarrhea"
* $nemsis-procedures#9914121 "Medical-Hyperglycemia"
* $nemsis-procedures#9914123 "Medical-Hypertension"
* $nemsis-procedures#9914125 "Medical-Hypoglycemia/Diabetic Emergency"
* $nemsis-procedures#9914127 "Medical-Hypotension/Shock (Non-Trauma)"
* $nemsis-procedures#9914129 "Medical-Influenza-Like Illness/Upper Respiratory Infection"
* $nemsis-procedures#9914131 "Medical-Nausea/Vomiting"
* $nemsis-procedures#9914133 "Medical-Newborn/Neonatal Resuscitation"
* $nemsis-procedures#9914135 "General-Overdose/Poisoning/Toxic Ingestion"
* $nemsis-procedures#9914137 "Medical-Pulmonary Edema/CHF"
* $nemsis-procedures#9914139 "Medical-Respiratory Distress/Asthma/COPD/Reactive Airway"
* $nemsis-procedures#9914141 "Medical-Seizure"
* $nemsis-procedures#9914143 "Medical-ST-Elevation Myocardial Infarction (STEMI)"
* $nemsis-procedures#9914145 "Medical-Stroke/TIA"
* $nemsis-procedures#9914147 "Medical-Supraventricular Tachycardia (Including Atrial Fibrillation)"
* $nemsis-procedures#9914149 "Medical-Syncope"
* $nemsis-procedures#9914151 "Medical-Ventricular Tachycardia (With Pulse)"
* $nemsis-procedures#9914153 "Not Done"
* $nemsis-procedures#9914155 "OB/GYN-Childbirth/Labor/Delivery"
* $nemsis-procedures#9914157 "OB/GYN-Eclampsia"
* $nemsis-procedures#9914159 "OB/GYN-Gynecologic Emergencies"
* $nemsis-procedures#9914161 "OB/GYN-Pregnancy Related Emergencies"
* $nemsis-procedures#9914163 "OB/GYN-Post-partum Hemorrhage"
* $nemsis-procedures#9914165 "Other"
* $nemsis-procedures#9914167 "Exposure-Carbon Monoxide"
* $nemsis-procedures#9914169 "Cardiac Arrest-Do Not Resuscitate"
* $nemsis-procedures#9914171 "Cardiac Arrest-Special Resuscitation Orders"
* $nemsis-procedures#9914173 "Exposure-Smoke Inhalation"
* $nemsis-procedures#9914175 "General-Community Paramedicine/Mobile Integrated Healthcare"
* $nemsis-procedures#9914177 "General-Exception Protocol"
* $nemsis-procedures#9914179 "General-Extended Care Guidelines"
* $nemsis-procedures#9914181 "General-Interfacility Transfers"
* $nemsis-procedures#9914183 "General-Law Enforcement - Blood for Legal Purposes"
* $nemsis-procedures#9914185 "General-Law Enforcement - Assist with Law Enforcement Activity"
* $nemsis-procedures#9914187 "General-Neglect or Abuse Suspected"
* $nemsis-procedures#9914189 "General-Refusal of Care"
* $nemsis-procedures#9914191 "Injury-Mass/Multiple Casualties"
* $nemsis-procedures#9914193 "Injury-Thoracic"
* $nemsis-procedures#9914195 "Medical-Adrenal Insufficiency"
* $nemsis-procedures#9914197 "Medical-Apparent Life Threatening Event (ALTE)"
* $nemsis-procedures#9914199 "Medical-Tachycardia"
* $nemsis-procedures#9914201 "Cardiac Arrest-Determination of Death/Withholding Resuscitative Efforts"
* $nemsis-procedures#9914203 "Injury-Conducted Electrical Weapon (e.g., Taser)"
* $nemsis-procedures#9914205 "Injury-Facial Trauma"
* $nemsis-procedures#9914207 "Injury-General Trauma Management"
* $nemsis-procedures#9914209 "Injury-Lightning/Lightning Strike"
* $nemsis-procedures#9914211 "Injury-SCUBA Injury/Accidents"
* $nemsis-procedures#9914213 "Injury-Topical Chemical Burn"
* $nemsis-procedures#9914215 "Medical-Beta Blocker Poisoning/Overdose"
* $nemsis-procedures#9914217 "Medical-Calcium Channel Blocker Poisoning/Overdose"
* $nemsis-procedures#9914219 "Medical-Opioid Poisoning/Overdose"
* $nemsis-procedures#9914221 "Medical-Respiratory Distress-Bronchiolitis"
* $nemsis-procedures#9914223 "Medical-Respiratory Distress-Croup"
* $nemsis-procedures#9914225 "Medical-Stimulant Poisoning/Overdose"
